### ISSUE TITLE
iOS push no longer possible on IMAP?

### ISSUE THREAD

**Issue by tmikaeld** [cullum/dank-selfhosted#1]
Thanks for sharing this project, It looks great especially for those security conscious self hosters out there!

I stumbled in here due to your Dovecot IMAP Patches and also saw that Apple suddenly stopped supporting that...

.. does that mean IMAP IDLE/PUSH on iOS is no longer possible on non-cloud mail servers?

**Comment by cullum** [comment]
It is apparently still possible - I know FastMail uses this mechanism to allow native push notifications - but I have no idea how mere mortals like me are supposed to get the APNS certificates now that OS X Server is basically a dead product.

My last certificate expired recently, so I no longer maintain the patch set.

If you or anyone else ever figures it out, please let me know!

**Comment by essandess** [comment]
@cullum See https://github.com/matthewpowell/pushnotify/issues/1

I believe it may be possible to create APNS certificates **without** Server.app for OpenBSD mail servers at https://identity.apple.com/pushcert/.

I haven’t worked the details yet, but if you have a running server patched to handle APNS, it’s a quick test to generate a signing certificate in Keychain Access’s Certificate Assistant, then generate a certificate signing request, post it to https://identity.apple.com/pushcert/, and use the resulting cert in the mail server’s configuration.

What are your thoughts on this moving forward without a functioning Server.app in Mojave?

Are you aware of comparable push notification patches for Calendar and Contact servers?

**Comment by essandess** [comment]
See these posts for successful reports of using pre-Mojave Server.app v. 5.7 to generate APNS certificates for use on upgraded servers:

* https://github.com/st3fan/dovecot-xaps-daemon/issues/46#issuecomment-469708103
* https://github.com/matthewpowell/pushnotify/issues/1#issuecomment-469969653
